spring:
  application:
    name: test-builder
  datasource:
    url: jdbc:h2:mem:security-security
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

token:
  signing:
    key: ${TOKEN_KEY}

org.springframework.boot.autoconfigure.security: INFO
logging:
  level:
    com.mzfk.test.builder: DEBUG
    org.springframework.security: INFO
    zalando.logbook: DEBUG