spring:
  application:
    name: test-builder
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2.console.enabled: true
  h2.console.path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

token:
  signing:
    key: ${TOKEN_KEY}

org.springframework.boot.autoconfigure.security: INFO
logging:
  level:
    com.mzfk.test.builder: DEBUG
    org.springframework.security: INFO
    zalando.logbook: DEBUG